name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.19
          pip install kivy
          pip install bleak

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          build-tools: 29.0.3
          ndk-version: 21.3.6528147

      - name: Export ANDROID_HOME environment variable
        run: echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Add Android SDK tools to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/build-tools/29.0.3" >> $GITHUB_ENV

      - name: Use Buildozer action
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          command: "android debug"
          repository_root: "."
          workdir: "."

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-kivy-app
          path: bin/*.apk
