name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.19
          pip install kivy
          pip install bleak

      - name: Install Buildozer and Android SDK
        run: |
          apt-get update
          apt-get install -y wget openjdk-8-jdk
          pip install buildozer
          wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O android-commandline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip android-commandline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        env:
          ANDROID_HOME: $HOME/android-sdk
          PATH: $PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/29.0.3

      - name: Use Buildozer action
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          command: "android debug"
          repository_root: "."
          workdir: "."

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-kivy-app
          path: bin/*.apk
