name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.19
        pip install kivy
        pip install bleak

    - name: Install Buildozer and Android SDK
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk wget
        pip install buildozer
        wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O android-commandline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip android-commandline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
        yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        
    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/build-tools/29.0.3" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Modify buildozer.spec
      run: |
        sed -i 's/python3==3.8/python3==3.8/g' buildozer.spec
        sed -i 's/^# \(android\.ndk_path = \)/\1\/opt\/android\/ndk/g' buildozer.spec
        sed -i 's/^# \(android\.sdk_path = \)/\1\/opt\/android\/sdk/g' buildozer.spec
        sed -i 's/^# \(requirements = python3,kivy\)/requirements = python3,kivy,bleak/g' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-kivy-app
        path: bin/*.apk
