name: Build APK

on:
  push:
    branches:
      - main  # Thực hiện khi có push lên nhánh main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install buildozer cython

    - name: Build APK
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev
        buildozer android debug
      env:
        ANDROIDSDK: ${{ secrets.ANDROIDSDK }}
        ANDROIDNDK: ${{ secrets.ANDROIDNDK }}
        ANDROIDAPI: ${{ secrets.ANDROIDAPI }}
        ANDROIDMINAPI: ${{ secrets.ANDROIDMINAPI }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: bin/*.apk
